const ITEMS = [

// ===== GS6 =====
{code:"GS6-H01", class:"GS6", type:"Collocation", format:"html", title:"Unit 1 – Test Collocation 50 câu", link:"https://phamnhu021200-bot.github.io/gs6-unit1-collocation-test/", note:"Đang có dữ liệu học sinh làm bài thật"},
{code:"GS6-H04", class:"GS6", type:"Grammar", format:"html", title:"Unit 1 – Chia động từ hiện tại đơn (bản A)", link:"https://phamnhu021200-bot.github.io/quiz-gr6-u1-verb/", note:"Trùng nội dung với GS6-H05 — nên giữ 1 bản"},
{code:"GS6-H05", class:"GS6", type:"Grammar", format:"html", title:"Unit 1 – Chia động từ hiện tại đơn (bản B)", link:"https://phamnhu021200-bot.github.io/quiz-gr6-unit1-verb/", note:"Trùng nội dung với GS6-H04 — nên giữ 1 bản"},
{code:"GS6-H06", class:"GS6", type:"Grammar", format:"html", title:"Unit 1 – My New School: Thì hiện tại đơn theo cấp độ (8 tầng)", link:"https://nhup3747-sys.github.io/gs6-hien-tai-don-phan-tang/"},
{code:"GS6-D08", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 1 – My New School: Đề kiểm tra (GS6_Unit1_Test)", link:"https://docs.google.com/document/d/127sT41ohRJIDwz_SgksRsK3MoCzDOteBHaeonJt3W4U/view"},
{code:"GS6-D09", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 1 – My New School: Đề kiểm tra lớp 6 (bản mới nhất)", link:"https://docs.google.com/document/d/18BTlo6LX0i81Vt6h9dEtkpcje-c9WGlB_Z-8hVvV7oE/view"},
{code:"GS6-D10", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 1 – My New School: Unit Test (bản cũ T7–8)", link:"https://docs.google.com/document/d/1YzybijBf4qg1Gs6compc7elubVcvO6_zsP9EpwCkI9s/view"},
{code:"KH-H04", class:"GS6", type:"Vocabulary", format:"html", title:"Từ vựng chủ đề Nhà cửa (My House)", link:"https://phamnhu021200-bot.github.io/quiz-myhouse/"},
{code:"GS6-D01", class:"GS6", type:"Vocabulary", format:"docx", title:"Unit 2 – My House: Kiểm tra từ vựng U2.1 (mẫu đề)", link:"https://drive.google.com/file/d/1NRcKrsJGyu64IYOE5ysa6qBzSzhDIsUD/view"},
{code:"GS6-D02", class:"GS6", type:"Vocabulary", format:"docx", title:"Unit 2 – My House: Kiểm tra từ vựng (07/10)", link:"https://drive.google.com/file/d/1tki-IQC-2KzRZWFkcI39fc4T4hn5bGL0/view"},
{code:"GS6-D03", class:"GS6", type:"Grammar", format:"docx", title:"Unit 2 – My House: Kiểm tra ngữ pháp (07/10)", link:"https://drive.google.com/file/d/1vZdzHeugKOi5LJ9sl3N-c7n95XvLURc4/view"},
{code:"GS6-D04", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 2 – My House: Kiểm tra tổng hợp (07/10, bản 08:38 – mới nhất)", link:"https://drive.google.com/file/d/1nMKh35WXNNJwduAamiSV_JRSzzygK5eV/view", note:"1 trong 4 bản cùng tên (GS6-D04→D07) — cô chọn bản chốt"},
{code:"GS6-D05", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 2 – My House: Kiểm tra tổng hợp (07/10, bản 08:34)", link:"https://drive.google.com/file/d/1Oj7vscdJ4hNRF_RnvarHEyVydamIRCQA/view", note:"Bản nháp cùng tên với GS6-D04 — cô chọn bản chốt"},
{code:"GS6-D06", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 2 – My House: Kiểm tra tổng hợp (07/10, bản 08:32)", link:"https://drive.google.com/file/d/12QXw1gq0pvao_ns2p_CDoYdKot95bp_N/view", note:"Bản nháp cùng tên với GS6-D04 — cô chọn bản chốt"},
{code:"GS6-D07", class:"GS6", type:"Tổng hợp", format:"docx", title:"Unit 2 – My House: Kiểm tra tổng hợp (07/10, bản không đuôi)", link:"https://drive.google.com/file/d/1EmPVAFRUehGjwr2tufYOGO_IRUoBCLx0/view", note:"Bản nháp cùng tên với GS6-D04 — cô chọn bản chốt"},
{code:"GS6-H02", class:"GS6", type:"Grammar", format:"html", title:"Chia động từ thì hiện tại đơn", link:"https://phamnhu021200-bot.github.io/quiz-gr6-chia-dong-tu/"},
{code:"GS6-H03", class:"GS6", type:"Grammar", format:"html", title:"Thì hiện tại đơn – Global Success", link:"https://phamnhu021200-bot.github.io/quiz-gr6-sp-basic/"},
{code:"GS6-H07", class:"GS6", type:"Grammar", format:"html", title:"Thì hiện tại tiếp diễn – ôn tập mất gốc (50 câu)", link:"https://nhup3747-sys.github.io/gs6-hien-tai-tiep-dien-mat-goc/"},
{code:"GS6-H08", class:"GS6", type:"Grammar", format:"html", title:"Luyện tập ngữ pháp cơ bản lớp 6 (5 dạng lỗi thường gặp)", link:"https://nhup3747-sys.github.io/gs6-on-tap-ngu-phap-co-ban/"},
{code:"GS6-H09", class:"GS6", type:"Grammar", format:"html", title:"Test Giới từ chỉ thời gian & nơi chốn (bản A)", link:"https://nhup3747-sys.github.io/gs6-prepositions-time-place/", note:"Nghi trùng GS6-H10 — nên giữ 1 bản"},
{code:"GS6-H10", class:"GS6", type:"Grammar", format:"html", title:"Test Giới từ chỉ thời gian & nơi chốn (bản B)", link:"https://nhup3747-sys.github.io/gs6-prepositions-time-place-test/", note:"Nghi trùng GS6-H09 — nên giữ 1 bản"},
{code:"GS6-H11", class:"GS6", type:"Vocabulary", format:"html", title:"Test Từ đồng nghĩa & trái nghĩa", link:"https://nhup3747-sys.github.io/gs6-tu-dong-nghia-trai-nghia/"},
{code:"GS6-D11", class:"GS6", type:"Grammar", format:"docx", title:"Bài tập thì hiện tại tiếp diễn", link:"https://docs.google.com/document/d/1G753poVEzMWljMgd021zpuuK1_wZRKtrAtF_fwX-GLw/view"},
{code:"GS6-D12", class:"GS6", type:"Vocabulary", format:"docx", title:"Danh sách từ vựng GS6 Book 1", link:"https://docs.google.com/document/d/1WnbZpP8v9lcxXAJ3CNZdLjCz1tJGXm-DBa6v9LPfzkQ/view"},

// ===== GS7 =====
{code:"GS7-H03", class:"GS7", type:"Tổng hợp", format:"html", title:"Unit 1 – Hobbies: Ôn tập tổng hợp", link:"https://nhup3747-sys.github.io/gs7-unit1-hobbies/"},
{code:"GS7-H04", class:"GS7", type:"Grammar", format:"html", title:"Unit 1 – Hobbies: Ôn tập ngữ pháp (HTĐ + verbs of liking)", link:"https://nhup3747-sys.github.io/gs7-unit1-on-tap-ngu-phap/"},
{code:"GS7-H05", class:"GS7", type:"Word Form", format:"html", title:"Unit 1 – Hobbies: Word Form", link:"https://nhup3747-sys.github.io/gs7-unit1-word-form/"},
{code:"GS7-H02", class:"GS7", type:"Grammar", format:"html", title:"Unit 3 – Community Service: Thì quá khứ đơn theo level (50 câu)", link:"https://nhup3747-sys.github.io/gs7-past-simple-levels/"},
{code:"GS7-H01", class:"GS7", type:"Grammar", format:"html", title:"Luyện tập 3 thì: HTĐ · QKĐ · HTTD", link:"https://nhup3747-sys.github.io/gs7-3-thi-nhan-biet/"},

// ===== GS8 =====
{code:"KH-H03", class:"GS8", type:"Vocabulary", format:"html", title:"Từ vựng chủ đề Giải trí (Leisure)", link:"https://phamnhu021200-bot.github.io/quiz-leisure/"},
{code:"GS8-D03", class:"GS8", type:"Vocabulary", format:"docx", title:"Unit 1–6: Danh sách từ vựng (Book 1)", link:"https://drive.google.com/file/d/1Q_wUJ5rQNMX90aPXIyFnO--uDTy2R9mN/view"},
{code:"GS8-D01", class:"GS8", type:"Vocabulary", format:"docx", title:"Unit 2: Kiểm tra từ vựng U2.1 (Word)", link:"https://drive.google.com/file/d/1ZuvDcYHppR5-D_2ystfQm9udw3-pgkKT/view", note:"Nghi trùng GS8-D02 (bản Google Docs) — nên giữ 1 bản"},
{code:"GS8-D02", class:"GS8", type:"Vocabulary", format:"docx", title:"Unit 2: Kiểm tra từ vựng U2.1 (Google Docs)", link:"https://docs.google.com/document/d/1wYGPPjj2nkz1NE_NEy5Gdp19BTmSfudoLmEcS70dhdA/view", note:"Nghi trùng GS8-D01 (bản Word) — nên giữ 1 bản"},
{code:"GS8-H01", class:"GS8", type:"Tổng hợp", format:"html", title:"Unit 3 – Teenagers: Bài tập củng cố", link:"https://nhup3747-sys.github.io/gs8-unit3-teenagers/"},

// ===== GS9 =====
{code:"GS9-D01", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 1 – Local Community (Vocab + Bài tập)", link:"https://drive.google.com/file/d/1TebqkBckc4zwy7L4tfNT3EawI7_8_InL/view"},
{code:"GS9-V01", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 1 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/1IdcCU7Sh1PnL7C6fwdXJCxvKFYh8ZKRU/view"},
{code:"GS9-C01", class:"GS9", type:"Collocation", format:"docx", title:"Unit 1 – Bảng Collocation tham khảo (84 cụm)", link:"https://docs.google.com/document/d/1hqfgEVx-xP-c-FMisB17YID8YMWqUlUpgxNCTTgJP2Y/view"},
{code:"GS9-H01", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Test Collocation hằng ngày, Tuần 1 (5 bài × 30 câu)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/", note:"Đang dùng — có chấm điểm, khóa theo ngày, gửi báo cáo email"},
{code:"GS9-H02", class:"GS9", type:"Word Form", format:"html", title:"Unit 1 – Test Word Form (5 tầng độ khó)", link:"https://phamnhu021200-bot.github.io/gs9-u1-wordform-test/"},
{code:"GS9-H03", class:"GS9", type:"Vocabulary", format:"html", title:"Unit 1 – Test từ vựng Level 2.5", link:"https://phamnhu021200-bot.github.io/quiz-gs9-u1-tuvung-level25/"},
{code:"KH-H10", class:"GS9", type:"Word Form", format:"html", title:"Xác định từ loại – Unit 1", link:"https://phamnhu021200-bot.github.io/quiz-tu-loai-unit1/"},
{code:"GS9-H07", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Local Community – Test Collocation Tuần 1, Bài 1/5 (Thứ Hai)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/Unit1_Test1_Tuan1.html"},
{code:"GS9-H08", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Local Community – Test Collocation Tuần 1, Bài 2/5 (Thứ Ba)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/Unit1_Test2_Tuan1.html"},
{code:"GS9-H09", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Local Community – Test Collocation Tuần 1, Bài 3/5 (Thứ Tư)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/Unit1_Test3_Tuan1.html"},
{code:"GS9-H10", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Local Community – Test Collocation Tuần 1, Bài 4/5 (Thứ Năm)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/Unit1_Test4_Tuan1.html"},
{code:"GS9-H11", class:"GS9", type:"Collocation", format:"html", title:"Unit 1 – Local Community – Test Collocation Tuần 1, Bài 5/5 (Thứ Sáu)", link:"https://phamnhu021200-bot.github.io/gs9-u1-collocation-test-tuan1/Unit1_Test5_Tuan1.html"},
{code:"GS9-H28", class:"GS9", type:"Grammar", format:"html", title:"Unit 1 & 2: Ôn tập ngữ pháp (wh-word + to-inf, so sánh)", link:"https://nhup3747-sys.github.io/gs9-unit1-2-on-tap-ngu-phap/"},
{code:"GS9-D08", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 1–3: Đáp án đề cương ôn tập giữa kỳ I", link:"https://docs.google.com/document/d/1-0naksundwxVqoHYqytzEX7A6uzmhKJ1ud6kG0InbzU/view"},
{code:"GS9-D09", class:"GS9", type:"Collocation", format:"docx", title:"Unit 1 – Bảng Collocation Local Community (Word)", link:"https://drive.google.com/file/d/1XyXgAR6pQLoGanaWYgBto7wiPS6GnpWQ/view", note:"Nghi trùng GS9-C01 (bản Google Docs) — nên giữ 1 bản"},
{code:"GS9-D10", class:"GS9", type:"Collocation", format:"docx", title:"Unit 1 – Bảng Collocation Local Community (Word, bản nhỏ)", link:"https://drive.google.com/file/d/13WvN-L5h6-M7GjEX3Be2bfYCtz6HcB_n/view", note:"Nghi bản nháp của GS9-D09 — nên giữ 1 bản"},
{code:"GS9-D02", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 2 – City Life (Vocab + Bài tập)", link:"https://drive.google.com/file/d/1t6-to4sQhaSkmzLaWc1e8tMOUmjAmYGS/view"},
{code:"GS9-V02", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 2 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/1AN-XuJQH5V1VgEZMUW_2R9d2N2fqEB8I/view"},
{code:"GS9-H23", class:"GS9", type:"Grammar", format:"html", title:"Unit 2 – City Life: BTVN viết lại câu (so sánh kép & cụm động từ)", link:"https://nhup3747-sys.github.io/gs9-btvn-viet-lai-cau-unit2/"},
{code:"GS9-H26", class:"GS9", type:"Grammar", format:"html", title:"Unit 2 – City Life: So sánh kép & tìm lỗi sai (50 câu)", link:"https://nhup3747-sys.github.io/gs9-ng-ph-p-u2/bai_tap_so_sanh_kep_unit2.html"},
{code:"GS9-H29", class:"GS9", type:"Tổng hợp", format:"html", title:"Unit 2 – City Life: Ôn tập tổng hợp", link:"https://nhup3747-sys.github.io/gs9-unit2-city-life/"},
{code:"GS9-H30", class:"GS9", type:"Grammar", format:"html", title:"Unit 2 – City Life: Kiểm tra so sánh kép & tìm lỗi sai", link:"https://nhup3747-sys.github.io/gs9-unit2-double-comparative-error-test/"},
{code:"GS9-H31", class:"GS9", type:"Word Form", format:"html", title:"Unit 2 – City Life: Kiểm tra Word Form", link:"https://nhup3747-sys.github.io/gs9-unit2-wordform-test/"},
{code:"GS9-D07", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 2 – City Life: Test 3 (bản học sinh)", link:"https://drive.google.com/file/d/1e4K0dJQXJN9bXUao0HN9Ft9ov819c1ES/view"},
{code:"GS9-D03", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 3 – Healthy Living for Teens (Vocab + Bài tập)", link:"https://drive.google.com/file/d/1LWSpq4QQXjixT9ue_4rMqYvyhNDMX99i/view"},
{code:"GS9-V03", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 3 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/1-X5S2KMHaCR6BNYEJUwQbHMsf670IlwH/view"},
{code:"GS9-H25", class:"GS9", type:"Grammar", format:"html", title:"Unit 3 – Modal verbs in First Conditional (32 câu, 4 cấp độ)", link:"https://nhup3747-sys.github.io/gs9-modal-first-conditional/"},
{code:"GS9-D04", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 4 – Remembering the Past (Vocab + Bài tập)", link:"https://drive.google.com/file/d/15x7sebkyirwjblod67R5j93N36T0RJVT/view"},
{code:"GS9-V04", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 4 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/193_nYN8J3wQsBLBuK6SbJ2IPNsqSO_qK/view"},
{code:"GS9-D05", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 5 – Our Experiences (Vocab + Bài tập)", link:"https://drive.google.com/file/d/1UMuYnTp9RxpTusmpPrlUDTh5iXWO3lAF/view"},
{code:"GS9-V05", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 5 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/10xwgkiAVYUIKlyPvEDQYAOi9YUrMPg2O/view"},
{code:"GS9-D06", class:"GS9", type:"Tổng hợp", format:"docx", title:"Unit 6 – Vietnamese Lifestyle: Then and Now (Vocab + Bài tập)", link:"https://drive.google.com/file/d/1lg3l3UaLbfNJI6qS-Ewz80n3YdUI_1s0/view"},
{code:"GS9-V06", class:"GS9", type:"Vocabulary", format:"docx", title:"Unit 6 – Vocabulary (bản chỉ từ vựng)", link:"https://drive.google.com/file/d/1AxoP0SuDquZmtZ0CKkJ779fggyAnmMj-/view"},
{code:"GS9-H04", class:"GS9", type:"Collocation", format:"html", title:"Local Community – Test 50 câu (bản cũ)", link:"https://phamnhu021200-bot.github.io/quiz-localcommunity-50/", note:"Có thể trùng nội dung với GS9-H01, nên kiểm tra và xoá bớt"},
{code:"GS9-H05", class:"GS9", type:"Grammar", format:"html", title:"Test Question Word + To-infinitive", link:"https://phamnhu021200-bot.github.io/quiz-gs9-questionword-toinfinitive/"},
{code:"GS9-H06", class:"GS9", type:"Grammar", format:"html", title:"Simple Present vs Present Continuous", link:"https://phamnhu021200-bot.github.io/quiz-gr9-sp-pc/"},
{code:"KH-H09", class:"GS9", type:"Grammar", format:"html", title:"Nhận biết các thì", link:"https://phamnhu021200-bot.github.io/quiz-nhanbietthi/"},
{code:"GS9-H12", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề trắc nghiệm số 1 (câu 1–100)", link:"https://nhup3747-sys.github.io/-1-tr-c-nghi-m-tuy-n-sinh-9--100-c-u/de_trac_nghiem_1.html"},
{code:"GS9-H13", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề trắc nghiệm số 2", link:"https://nhup3747-sys.github.io/-1-tr-c-nghi-m-tuy-n-sinh-9--100-c-u/de_trac_nghiem_2.html"},
{code:"GS9-H14", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề trắc nghiệm số 3", link:"https://nhup3747-sys.github.io/-1-tr-c-nghi-m-tuy-n-sinh-9--100-c-u/de_trac_nghiem_3.html"},
{code:"GS9-H15", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề trắc nghiệm số 4 (câu 301–407)", link:"https://nhup3747-sys.github.io/-1-tr-c-nghi-m-tuy-n-sinh-9--100-c-u/de_trac_nghiem_4.html"},
{code:"GS9-H16", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề số 2 TPHCM 2025–2026", link:"https://nhup3747-sys.github.io/-2-TUY-N-SINH/de2_hcm_2026%20(1).html"},
{code:"GS9-H17", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề tham khảo THCS Linh Trung 2026–2027", link:"https://nhup3747-sys.github.io/-e-THCS-linh-trung/de_thcs_linh_trung.html"},
{code:"GS9-H18", class:"GS9", type:"Grammar", format:"html", title:"Ôn thi vào 10 – 222 câu trắc nghiệm ngữ pháp TPHCM", link:"https://nhup3747-sys.github.io/222-cau-trac-nghiem-tuyen-sinh-TPHCM/222_cau_trac_nghiem.html"},
{code:"GS9-H19", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề dự đoán số 1 TPHCM 2026–2027", link:"https://nhup3747-sys.github.io/de-1-du-doan-/de1_hcm_2026_2027.html"},
{code:"GS9-H20", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề dự đoán số 2 TPHCM 2026–2027 (bản 17/05)", link:"https://nhup3747-sys.github.io/de-2-du-doan/de2_hcm_2026_2027.html", note:"Nghi trùng GS9-H21 (bản 19/05) — nên giữ 1 bản"},
{code:"GS9-H21", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 – Đề dự đoán số 2 TPHCM 2026–2027 (bản 19/05)", link:"https://nhup3747-sys.github.io/de-2-du-doan-2/de2_hcm_2026_2027.html", note:"Nghi trùng GS9-H20 (bản 17/05) — nên giữ 1 bản"},
{code:"GS9-H22", class:"GS9", type:"Tổng hợp", format:"html", title:"Ôn thi vào 10 TPHCM – Bộ đề trắc nghiệm có gợi ý", link:"https://nhup3747-sys.github.io/t-ng-h-p-c-c-n/"},
{code:"GS9-H24", class:"GS9", type:"Grammar", format:"html", title:"Mệnh đề If: hiện tại đơn & modal verb", link:"https://nhup3747-sys.github.io/gs9-if-clause-drill/"},
{code:"GS9-H27", class:"GS9", type:"Vocabulary", format:"html", title:"Tính từ bổ trợ – lớp 9 nền tảng", link:"https://nhup3747-sys.github.io/gs9-tinh-tu-bo-tro/"},

// ===== GS11 =====
{code:"GS11-D01", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 1 (bản HS)", link:"https://drive.google.com/file/d/1MOqeSem1MVAfWXFgLnxR0E8K8GWZ1IX7/view"},
{code:"GS11-D02", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 1 (bản GV)", link:"https://drive.google.com/file/d/1Q3kuPS-CcrOp5YKKVQwSG_Q4Uz16MQSD/view", note:"Bản giáo viên có đáp án — cô cân nhắc quyền chia sẻ"},
{code:"GS11-D03", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 2 (bản HS)", link:"https://drive.google.com/file/d/13LC1RSIzJ1tM2nrJMC4YeIXMBNH417YA/view"},
{code:"GS11-D04", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 2 (bản GV)", link:"https://drive.google.com/file/d/1s5suwWmbFdcS3o6UkJhMwR3F82w6p4gL/view", note:"Bản giáo viên có đáp án — cô cân nhắc quyền chia sẻ"},
{code:"GS11-D05", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 3 (bản HS)", link:"https://drive.google.com/file/d/12CBG6Tn2NFwGsPWZXITa_msbzt3Pqvp1/view"},
{code:"GS11-D06", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: TEST 3 (bản GV)", link:"https://drive.google.com/file/d/134ZV8sXrp2hMhWEjnVaxYj0JdKhBDAoy/view", note:"Bản giáo viên có đáp án — cô cân nhắc quyền chia sẻ"},
{code:"GS11-D07", class:"GS11", type:"Tổng hợp", format:"docx", title:"Unit 1 – A Long and Healthy Life: Test 1 (bản HS, .docx)", link:"https://drive.google.com/file/d/1W8JGAnH40lk1rOTNDmAMkVQ746DATfTH/view"},
{code:"GS11-D08", class:"GS11", type:"Vocabulary", format:"docx", title:"Unit 1 – A Long and Healthy Life: Kiểm tra từ vựng U1.1", link:"https://drive.google.com/file/d/1LAl8M3b74GkRcptH4wvYlpxUL1vEfRLS/view"},
{code:"GS11-D09", class:"GS11", type:"Vocabulary", format:"docx", title:"Unit 1 – A Long and Healthy Life: Kiểm tra từ vựng U1.2", link:"https://drive.google.com/file/d/1GCgSGoeLSgFoF1JdqPcsPw5i6kg-65W5/view"},
{code:"GS11-D10", class:"GS11", type:"Collocation", format:"docx", title:"Unit 1 – Vocabulary & Collocations U1.1", link:"https://drive.google.com/file/d/1GGPZINm5KaEq9xHOUMgaaqkjuGUh-aj9/view"},
{code:"GS11-D11", class:"GS11", type:"Collocation", format:"docx", title:"Unit 1 – Vocabulary & Collocations (bản đầu)", link:"https://drive.google.com/file/d/1C2XRcq8_2UrK0WUzzvQfffDh8PT2IfgD/view", note:"Nghi bản trước của GS11-D10 — nên giữ 1 bản"},
{code:"GS11-D12", class:"GS11", type:"Collocation", format:"docx", title:"Unit 1 – Vocabulary & Collocations: Yoga", link:"https://drive.google.com/file/d/1oVkdxIEz6BgHYmQk1-ZjFgMUMTH7TgBP/view"},
{code:"GS11-D13", class:"GS11", type:"Grammar", format:"docx", title:"Unit 1 – Test viết lại câu (bản 1)", link:"https://drive.google.com/file/d/1BQhkGRfiW6gzV06M8yKERzKCkKBkEvA2/view", note:"Có bản cập nhật GS11-D14 — nên giữ 1 bản"},
{code:"GS11-D14", class:"GS11", type:"Grammar", format:"docx", title:"Unit 1 – Test viết lại câu (bản 1.1)", link:"https://drive.google.com/file/d/1I0cHHZIj6PyeAf6crDn485vL21xHxL-1/view"},
{code:"GS11-D15", class:"GS11", type:"Grammar", format:"docx", title:"Kiểm tra 15 phút: Stative & Linking Verbs", link:"https://drive.google.com/file/d/1KH9HpFH_LPWPe-k90eDba49oL1BqAWSp/view"},
{code:"GS11-D16", class:"GS11", type:"Grammar", format:"docx", title:"Công thức viết lại câu", link:"https://drive.google.com/file/d/1CLJ9X_E-eJcESXCYRRil43QQeRqTzG59/view"},

// ===== Lớp 5 =====
{code:"TA5-H01", class:"Lớp 5", type:"Vocabulary", format:"html", title:"Từ vựng Unit 1 + Unit 2", link:"https://phamnhu021200-bot.github.io/quiz-gr5-u1u2-vocab/"},

// ===== Lớp nền tảng =====
{code:"LNT-D01", class:"Lớp nền tảng", type:"Word Form", format:"docx", title:"Unit 1 – Test Word Form số 2 (3 phần: từ loại, MCQ, điền dạng từ)", link:"https://drive.google.com/file/d/1ik4JfzayDmR0UnIcBiKfFwO7U2Rej4pr/view"},
{code:"LNT-H01", class:"Lớp nền tảng", type:"Phrasal Verb", format:"html", title:"Phrasal Verbs – Bài 1", link:"https://phamnhu021200-bot.github.io/quiz-lopnentang-phrasalverb-bai1/"},
{code:"LNT-H02", class:"Lớp nền tảng", type:"Grammar", format:"html", title:"Question Word + To-infinitive – 100 câu", link:"https://phamnhu021200-bot.github.io/quiz-lopnentang-questionword-toinfinitive/"},
{code:"LNT-D02", class:"Lớp nền tảng", type:"Grammar", format:"docx", title:"Question Word + To-infinitive – Đề luyện tập 1 (20 MCQ + 10 viết lại câu)", link:"https://drive.google.com/file/d/11DUb2HVINFpgyRRu4r3FL-6zPn2M785Y/view"},
{code:"LNT-D03", class:"Lớp nền tảng", type:"Grammar", format:"docx", title:"Question Word + To-infinitive – Đề luyện tập 2 (20 MCQ + 10 viết lại câu)", link:"https://drive.google.com/file/d/1WS04ryzSOkKephVeqfQPBoQ6AUD_Tl6t/view"},

// ===== IELTS =====
{code:"IE-H01", class:"IELTS", type:"Vocabulary", format:"html", title:"Từ vựng IELTS – Bộ 1", link:"https://phamnhu021200-bot.github.io/tu-vung-ielts-1/", note:"Có bản cập nhật IE-H02, nên kiểm tra bản nào mới hơn"},
{code:"IE-H02", class:"IELTS", type:"Vocabulary", format:"html", title:"Từ vựng IELTS – Bộ 1.1 (bản cập nhật)", link:"https://phamnhu021200-bot.github.io/tu-vung-ielts-1.1/"},

// ===== Chưa phân loại =====
{code:"KH-H01", class:"Chưa phân loại", type:"Vocabulary", format:"html", title:"Từ vựng chủ đề Gia đình (Family)", link:"https://phamnhu021200-bot.github.io/quiz-family/"},
{code:"KH-H02", class:"Chưa phân loại", type:"Vocabulary", format:"html", title:"Từ vựng chủ đề Sở thích (Hobbies)", link:"https://phamnhu021200-bot.github.io/quiz-hobbies/"},
{code:"KH-H05", class:"Chưa phân loại", type:"Vocabulary", format:"html", title:"Từ vựng chủ đề Trường học (School)", link:"https://phamnhu021200-bot.github.io/quiz-school-vocab/"},
{code:"KH-H06", class:"Chưa phân loại", type:"Grammar", format:"html", title:"Động từ TO BE", link:"https://phamnhu021200-bot.github.io/quiz-tobe/"},
{code:"KH-H07", class:"Chưa phân loại", type:"Grammar", format:"html", title:"TO BE – Câu phủ định (bản A)", link:"https://phamnhu021200-bot.github.io/quiz-tobe-phu-dinh/", note:"Trùng với KH-H08 — nên giữ 1 bản"},
{code:"KH-H08", class:"Chưa phân loại", type:"Grammar", format:"html", title:"TO BE – Câu phủ định (bản B)", link:"https://phamnhu021200-bot.github.io/quiz-tobe-phudinh/", note:"Trùng với KH-H07 — nên giữ 1 bản"},
{code:"KH-H11", class:"Chưa phân loại", type:"Grammar", format:"html", title:"4 thì cơ bản", link:"https://phamnhu021200-bot.github.io/quiz-4thi/"},
{code:"KH-H12", class:"Chưa phân loại", type:"Khác", format:"html", title:"test-1 (chưa rõ nội dung)", link:"https://phamnhu021200-bot.github.io/test-1/", note:"Không rõ mục đích — nên kiểm tra, xoá nếu không dùng"},
{code:"KH-H13", class:"Chưa phân loại", type:"Grammar", format:"html", title:"Gerund & Infinitive Quiz (20 câu)", link:"https://phamnhu021200-bot.github.io/test-1/gerund_infinitive_quiz.html", note:"Cần cô xem: đây là file thật của KH-H12 (link cũ 404) — không ghi khối, cô cho biết lớp"},
{code:"KH-H14", class:"Chưa phân loại", type:"Grammar", format:"html", title:"Tổng ôn ngữ pháp vào lớp 10 – Buổi 1", link:"https://nhup3747-sys.github.io/ngu-phap/tong_on_ngu_phap_buoi1.html", note:"Cần cô xem: trang ghi người biên soạn khác — ôn thi vào 10 (lớp 9)"},
{code:"KH-D01", class:"Chưa phân loại", type:"Grammar", format:"docx", title:"Bài tập viết lại câu (câu 41–50)", link:"https://docs.google.com/document/d/1YPTSr1YIjB7A4E4rdBIm5ZpavnQzxCA55wODtPeu8VM/view", note:"Cần cô xem: chưa rõ lớp — nội dung giống ôn thi vào 10"},
];
